sudo: required
language: bash
dist: xenial
services:
  - docker

script:
  # build the Docker image using the Docker tool, osc cannot be easily used in Travis
  - cd package
  - docker build -t yast-test-cpp-image -f Dockerfile .
  # check the Travis script
  - docker run -it --rm yast-test-cpp-image shellcheck /usr/local/bin/yast-travis-cpp

